### PR TITLE
Fix for Google

### PR DESCRIPTION
**Pull request by markguinn**
This allows it to work with just an access token.

### CODE REVIEW

**Comment by markguinn** [comment]
Sorry, I went from the master branch instead of develop which shouldn't hurt anything. I also forgot to check the tests. Will resubmit.

**Comment by markguinn** [comment]
I can't figure out how to mock that Google service properly. Any suggestions?

**Comment by 1blankz7** [comment]
I have mocked the client class in a separate branch.
https://github.com/notthatbad/silverstripe-rest-api-oauth/blob/google/tests/functional/GoogleSocialSessionEndpointTest.php

Because they exception is not properly handled, the test still fail. But this can be fixed easily with catching the Exception and throwing one of the internal ones.

**Comment by markguinn** [comment]
Brilliant. Feel free to scrap this PR and merge yours.

**Comment by 1blankz7** [comment]
Rejected in favor of #4

**Pull request closed without merging**
